name: Create a comment on a new issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: "create comment with API"
        run: |
          gh api -X POST \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Comment from API call
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
     
      - name: Debug Info
        run: |
          echo "Organization: ${{ github.event.organization.login }}"
          echo "Repository: ${{ github.event.repository.name }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
